name: straybud
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.9.2
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.10.0
  firebase_core: ^2.16.0
  firebase_storage: ^11.2.7
  flutter:
    sdk: flutter
  flutter_email_sender: ^6.0.1
  flutter_local_notifications: ^15.1.1
  flutter_phone_direct_caller: ^2.1.1
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.5.0
  google_fonts: ^5.1.0
  image_picker: ^1.0.4
  intl: ^0.18.1
  lottie: ^2.6.0
  mailer: ^6.0.1
  onesignal_flutter: ^5.0.1
  provider: ^6.0.1
  url_launcher: ^6.1.14
  uuid: ^3.0.5
  feedback: ^3.0.0
  wiredash: ^1.8.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/animations/1.json
    - lib/animations/feedback.json
    - lib/animations/search.json
    - lib/animations/upload.json
    - lib/animations/upload1.json
    - lib/animations/post.json
    - lib/images/apple.jpeg
    - lib/images/google.jpeg
    - lib/images/dog.jpeg
    - lib/images/data1.jpeg
    - lib/images/adopt.jpeg
    - lib/images/levi.jpeg
    - lib/images/pushpa.jpeg
    - lib/images/health.jpeg
    - lib/images/flutter.jpeg
    - lib/images/bleed.jpeg   
    - lib/images/burns.jpeg   
    - lib/images/choking.jpeg   
    - lib/images/search.jpeg
    - lib/images/optimization.jpeg
    - lib/images/Labrador.jpeg
    - lib/images/pomeranian.jpeg
    - lib/images/beagle.jpeg
    - lib/images/german.jpeg
    - assets/ic_instagram.svg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
